<head>
    <link href="../styles.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>Finance</title>
</head>
<header>
    <div class="container">
        <a href="/" class="logo">
            <img src="media/cool-monkey.jpeg" alt="Cool Monkey" width="150px">
        </a>
        <div id="menu">
        <nav>
            <ul>
                <li><a href="/rates">Rates</a></li>
                <li><a href="/finance">Finances</a></li>
                <li><a href="/finance_details">Details add</a></li>
                <li><a href="/diagrams">Diagrams</a></li>
                <li><a href="#">Additional</a>
                    <ul>
                        <li><a href="/meter_readings">Meter readings</a></li>
                        <li><a href="/vacation">Vacations</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        </div>
    </div>
</header>
