<?php
if (strpos($requestUrl, 'lovely') !== false) {
    $logoUrl = '/media/lovely-logo.png';
    $menuPoints =
        [
            [
                'url' => $serverUrl . '/lovely_space/product',
                'label' => 'Продукти',
            ],
            [
                'url' => $serverUrl . '/lovely_space/arrival',
                'label' => 'Прибуття',
            ],
            [
                'url' => $serverUrl . '/lovely_space/order',
                'label' => 'Замовлення',
            ],
            [
                'url' => $serverUrl . '/lovely_space/client',
                'label' => 'Клієнти',
            ],
        ];
} else {
    $logoUrl = '/media/cool-monkey.jpeg';
    $menuPoints =
        [
            [
                'url' => $serverUrl . '/finance_management/finance',
                'label' => 'Finances',
            ],
            [
                'url' => $serverUrl . '/finance_management/rates',
                'label' => 'Rates',
            ],
            [
                'url' => $serverUrl . '/finance_management/finance_details',
                'label' => 'Details add',
            ],
            [
                'url' => $serverUrl . '/finance_management/diagrams',
                'label' => 'Diagrams',
            ],
        ];
}
?>
<head>
    <link href="<?php echo $serverUrl; ?>/styles.css" rel="stylesheet">
    <link href="<?php echo $serverUrl; ?>/lovely.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>Finance</title>
</head>
<header>
    <div class="left">
        <div id="left-menu">
            <nav>
                <ul>
                    <li><a href="<?php echo $serverUrl; ?>/finance_management/finance">Finances</a></li>
                    <li><a href="<?php echo $serverUrl; ?>/lovely_space/product">Lovely space</a></li>
                </ul>
            </nav>
        </div>
    </div>

    <div class="container">
        <a href="/" class="logo">
            <img src="<?php echo $serverUrl . $logoUrl; ?>" alt="Cool Monkey" width="150px">
        </a>
        <div id="menu">
            <nav>
                <ul>
                    <?php foreach ($menuPoints as $menuPoint): ?>
                        <li><a href="<?php echo $menuPoint['url']; ?>"><?php echo $menuPoint['label']; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </nav>
        </div>
    </div>
</header>
