<?php
if (!(strpos($requestUrl, 'lovely') !== false || $requestUrl === '/')) {
    $logoUrl = '/media/cool-monkey.jpeg';
    $menuPoints =
        [
            [
                'url' => $serverUrl . '/finance',
                'label' => 'Finances',
            ],
            [
                'url' => $serverUrl . '/rates',
                'label' => 'Rates',
            ],
            [
                'url' => $serverUrl . '/finance_details',
                'label' => 'Details add',
            ],
            [
                'url' => $serverUrl . '/diagrams',
                'label' => 'Diagrams',
            ],
        ];
} else {
    $logoUrl = '/media/lovely-logo.png';
    $productUrl = '/lovely_space/product';
    $arrivalUrl = '/lovely_space/arrival';
    $orderUrl = '/lovely_space/order';
    $clientUrl = '/lovely_space/client';

    $menuPoints =
        [
            [
                'url' => $serverUrl . $productUrl,
                'label' => 'Продукти',
            ],
            [
                'url' => $serverUrl . $arrivalUrl,
                'label' => 'Прибуття',
            ],
            [
                'url' => $serverUrl . $orderUrl,
                'label' => 'Замовлення',
            ],
            [
                'url' => $serverUrl . $clientUrl,
                'label' => 'Клієнти',
            ],
        ];

    foreach ($menuPoints as $key => $value) {
        if (strpos($value['url'], $requestUrl) !== false) {
            $menuPoints[$key]['class'] = 'menu-chosen';
        } else {
            $menuPoints[$key]['class'] = '';
        }
    }
}
?>
<head>

    <link href="<?php echo $serverUrl; ?>/css/select2.min.css" rel="stylesheet" />
    <link href="<?php echo $serverUrl; ?>/css/styles.css" rel="stylesheet">
    <link href="<?php echo $serverUrl; ?>/css/lovely.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="<?php echo $serverUrl; ?>/js/lib/select2.js"></script>

    <link type="text/css" rel="stylesheet" href="<?php echo $serverUrl; ?>/css/jsgrid.css" />

    <script type="text/javascript" src="<?php echo $serverUrl; ?>/js/lib/jsgrid.js"></script>
    <title>Finance</title>
</head>
<header>
<!--    <div class="left">-->
<!--        <div id="left-menu">-->
<!--            <nav>-->
<!--                <ul>-->
<!--                    <li><a href="--><?php //echo $serverUrl; ?><!--/finance_management/finance">Finances</a></li>-->
<!--                    <li><a href="--><?php //echo $serverUrl; ?><!--/lovely_space/product">Lovely space</a></li>-->
<!--                </ul>-->
<!--            </nav>-->
<!--        </div>-->
<!--    </div>-->

    <div class="container">
        <a href="/" class="logo">
            <img src="<?php echo $serverUrl . $logoUrl; ?>" alt="Cool Monkey" width="150px">
        </a>
        <div id="menu">
            <nav>
                <ul>
                    <?php foreach ($menuPoints as $menuPoint): ?>
                        <li><a class="<?=$menuPoint['class'] ?>" href="<?php echo $menuPoint['url']; ?>"><?php echo $menuPoint['label'];
                        ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </nav>
        </div>
    </div>
</header>
<script>
</script>
