<?php
$logoUrl = '/media/lovely-logo.png';
$productUrl = '/lovely_space/product';
$arrivalUrl = '/lovely_space/arrival';
$orderUrl = '/lovely_space/order';
$clientUrl = '/lovely_space/client';
$shopUrl = '/lovely_space/shop';
$reportUrl = '/lovely_space/report';
$commentsUrl = '/lovely_space/comments';
$spendingUrl = '/lovely_space/spending';

$menuPoints =
    [
        [
            'url' => $serverUrl . $productUrl,
            'label' => 'Продукти',
        ],
        [
            'url' => $serverUrl . $arrivalUrl,
            'label' => 'Надходження',
        ],
        [
            'url' => $serverUrl . $orderUrl,
            'label' => 'Замовлення',
        ],
        [
            'url' => $serverUrl . $clientUrl,
            'label' => 'Клієнти',
        ],
        [
            'url' => $serverUrl . $shopUrl,
            'label' => 'Магазини',
        ],
        [
            'url' => $serverUrl . $reportUrl,
            'label' => 'Статистика',
        ],
        [
            'url' => $serverUrl . $spendingUrl,
            'label' => 'Витрати',
        ],
//        [
//            'url' => $serverUrl . $commentsUrl,
//            'label' => 'Коментарі',
//        ],
    ];


foreach ($menuPoints as $key => $value) {
    if ((strpos($value['url'], $requestUrl) !== false && $requestUrl !== '/')
        || ($requestUrl === '/' && $value['label'] === 'Продукти')
    ) {
        $menuPoints[$key]['class'] = 'menu-chosen';
    } else {
        $menuPoints[$key]['class'] = '';
    }
}
?>
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <link href="<?php echo $serverUrl; ?>/css/select2.min.css" rel="stylesheet" />
    <link href="<?php echo $serverUrl; ?>/css/select2-bootstrap.css" rel="stylesheet">
    <?php if (preg_match("/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i", $_SERVER["HTTP_USER_AGENT"])) :?>
        <link href="<?php echo $serverUrl; ?>/css/lovely_mobile.css" rel="stylesheet">
    <?php else: ?>
        <link href="<?php echo $serverUrl; ?>/css/styles.css" rel="stylesheet">
        <link href="<?php echo $serverUrl; ?>/css/lovely.css" rel="stylesheet">
    <?php endif; ?>
    <script src="<?php echo $serverUrl; ?>/js/lib/select2.js"></script>

    <link type="text/css" rel="stylesheet" href="<?php echo $serverUrl; ?>/css/jsgrid.css" />
    <script type="text/javascript" src="<?php echo $serverUrl; ?>/js/lib/jsgrid.js"></script>

    <title>Lovely space</title>
</head>
<header>
    <div class="container">
        <a href="/lovely_space/product" class="logo">
            <img src="<?php echo $serverUrl . $logoUrl; ?>" alt="Lovely space" width="200px">
        </a>
        <div id="menu">
            <div id="menu-open">MENU</div>
            <nav id="menu">
                <ul>
                    <?php foreach ($menuPoints as $menuPoint): ?>
                        <li>
                            <a class="<?= $menuPoint['class'] ?>" href="<?= $menuPoint['url']; ?>"><?= $menuPoint['label']; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </nav>
        </div>
    </div>
</header>
<script>
    jQuery(document).ready(function ($) {
        $('#menu #menu-open').click(function () {
            $('#menu nav#menu').toggle();
        });
    });
</script>
