<?php
session_start();
$serverUrl = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'];
$requestUrl = str_replace(stristr($_SERVER["REQUEST_URI"], '?'), '', $_SERVER["REQUEST_URI"]);

if(empty($_SESSION["authenticated"]) || $_SESSION["authenticated"] !== 'true') {
    include 'login.phtml';
} else {
    include 'require_once.phtml';
    include 'header.phtml';
    include 'main.phtml';
    include 'footer.phtml';
}
?>
