<body>
<div class="main">
    <div class="container">
        <?php

        if ($_SERVER['REQUEST_URI'] != '/') {
            $isLovelySpace = strpos($_SERVER['REQUEST_URI'], 'lovely_space') !== false;
            if ($isLovelySpace) {
                echo '<div id="lovely-space">';
            }
            include 'template' . $requestUrl . '.phtml';
            if ($isLovelySpace) {
                echo '</div>';
            }
        } else {
            include 'template/finance_management/finance.phtml';
            ?>
            <?php
        }
        ?>
    </div>
</div>
</body>
