<body>
<div class="main">
    <div class="container">
        <?php

        if ($_SERVER['REQUEST_URI'] != '/') {
            if ($isLovelySpace) {
                echo '<div id="lovely-space">';
                include 'template' . $requestUrl . '.phtml';
                echo '</div>';
            } else {
                include 'template/finance_management' . $requestUrl . '.phtml';
            }
        } else {
            echo '<div id="lovely-space">';
            include 'template/lovely_space/product.phtml';
            echo '</div>';
            ?>
            <?php
        }
        ?>
    </div>
</div>
</body>
