<?php
/** @var \classes\Model\Rate $rate */
$rate = \classes\ClassCreator::includeClass(\classes\Model\Rate::class);
$rates = $rate->getRates();
?>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Currency</th>
        <th>Coefficient</th>
    </tr>
    </thead>
    <tr>
    <?php
    foreach ($rates as $rate) {
        echo '<td>';
        echo $rate['id'];
        echo '</td>';
        echo '<td>';
        echo $rate['currency'];
        echo '</td>';
        echo '<td>';
        echo $rate['coefficient'];
        echo '</td>';
    }
    ?>
    </tr>
</table>
