<?php
/** @var \LovelySpace\Model\Product\ProductRepository $productRepository */
$productRepository = \ClassCreator::get(\LovelySpace\Model\Product\ProductRepository::class);
$products = $productRepository->getList();

/** @var \LovelySpace\Model\Shop\ShopRepository $shopRepository */
$shopRepository = \ClassCreator::get(\LovelySpace\Model\Shop\ShopRepository::class);
$shops = $shopRepository->getList();

/** @var \LovelySpace\Model\Arrival\ArrivalRepository $arrivalRepository */
$arrivalRepository = \ClassCreator::get(\LovelySpace\Model\Arrival\ArrivalRepository::class);

if (!empty($_POST)) {
    if (isset($_POST['delete']) && (bool)$_POST['delete'] === true) {
        $arrivalRepository->delete($_POST['id']);
    } else {
        $arrivalRepository->save($_POST);
    }

    header('Location: '. $serverUrl . '/lovely_space/arrival');
    die;
}

$arrivalId = null;
if (!empty($_GET)) {
    $arrivalId = isset($_GET['id']) ? $_GET['id'] : null;
}

/** @var \LovelySpace\Model\Arrival\Arrival $arrival */
$arrival = $arrivalRepository->get($arrivalId);

/** @var \LovelySpace\Model\Arrival\ArrivalItemRepository $arrivalItemRepository */
$arrivalItemRepository = \ClassCreator::get(\LovelySpace\Model\Arrival\ArrivalItemRepository::class);
$arrivalsItems = $arrivalItemRepository->getListByArrivalId($arrivalId);

/** @var \LovelySpace\Model\Resource\Arrival\ArrivalItem $arrivalItemResource */
$arrivalItemResource = \ClassCreator::get(\LovelySpace\Model\Resource\Arrival\ArrivalItem::class);
$lastCosts = [];
?>
<div class="title"><span class="title">Надходження</span></div>

<div id="add-product-to-arrival">
    <div id="add-product" class="full">
        <div class="full-with-margin">
        <label for="products"><span>Оберіть продукт<span></label>
        </div>
        <div class="full-with-margin">
        <select class="select2" id="products" name="products">
            <?php
            /** @var \LovelySpace\Model\Product\Product $product */
            foreach ($products as $product): ?>
                <option value="<?= $product->getId(); ?>"><?= $product->getName(); ?></option>
                <?php $lastCosts[$product->getId()] = $arrivalItemResource->getLastCostForProductByProductId($product->getId()); ?>
            <?php endforeach; ?>
        </select>
        </div>
    </div>
    <div class="full">
        <button id="add-product-button" class="near-select full">Додати</button>
    </div>

</div>

<form action="" method="post" id="edit">
    <table id="arrival-items-grid" class="full-part">
        <thead>
        <tr>
            <th class="product-name">Імя продукта</th>
            <th>Собівартість за одиницю</th>
            <th>Кількість одиниць</th>
            <th>Видалити</th>
        </tr>
            <?php
            /** @var \LovelySpace\Model\Arrival\ArrivalItem $arrivalsItem */
            foreach ($arrivalsItems as $arrivalsItem): ?>
                <tr>
                    <td><input type="text" id="name[<?= $arrivalsItem->getProductId(); ?>]" name="name[<?= $arrivalsItem->getProductId(); ?>]" value="<?= $arrivalsItem->getProductName(); ?>"></td>
                    <td><input type="number" id="cost[<?= $arrivalsItem->getProductId(); ?>]" name="cost[<?= $arrivalsItem->getProductId(); ?>]" value="<?= $arrivalsItem->getCost(); ?>"></td>
                    <td><input type="number" id="qty[<?= $arrivalsItem->getProductId(); ?>]" name="qty[<?= $arrivalsItem->getProductId(); ?>]" value="<?= $arrivalsItem->getQty(); ?>"></td>
                    <td><span id="delete"><img src="<?= $serverUrl; ?>/media/delete-icon.png" alt="Delete" width="20px"></span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </thead>
    </table>
    <div>
        <input type="number" id="id" name="id" value="<?= $arrival->getId(); ?>" style="display: none">
    </div>
    <div id="shop">
        <div class="full-with-margin">
            <label class="required" for="shop"><span>Магазин:<span></label>
        </div>
        <div class="full-with-margin">
            <select class="select2" id="shop" name="shop">
                <?php
                /** @var \LovelySpace\Model\Shop\Shop $shop */
                foreach ($shops as $shop): ?>
                    <?php $selected = $shop->getId() == $arrival->getShopId() ? 'selected' : '' ?>
                    <option <?= $selected; ?> value="<?= $shop->getId(); ?>"><?= $shop->getName(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</form>
<div>
    <button class="half" onclick="location.href = '<?= $_SERVER['HTTP_REFERER']?>'" id="back-button">Назад</button>
    <button class="half" form="edit" type="submit" id="save-arrival-button">Зберегти</button>
</div>
<?php if (null !== $arrivalId): ?>
<form action="" onsubmit="return confirm('Ви впевнені? Повернути дану дію буде неможливо.')" method="post" id="delete">
    <input type="number" id="delete" name="delete" value="1" style="display: none">
    <input type="number" id="id" name="id" value="<?= $arrival->getId(); ?>" style="display: none">
    <button class="full" id="delete">Видалити замовлення</button>
</form>
<?php endif; ?>

<script>
    var serverUrl = '<?= $serverUrl ?>',
        lastCosts = JSON.parse('<?= json_encode($lastCosts) ?>');

    jQuery(document).ready(function ($) {
        $("#add-product-to-arrival #add-product-button").on('click', function () {
            var trLength = document.getElementsByTagName("tr").length,
                table = document.getElementById("arrival-items-grid"),
                row = table.insertRow(trLength),
                productName = $('#add-product-to-arrival #products option:selected').text(),
                productId = $('#add-product-to-arrival #products option:selected').val(),
                alreadyExists = $('input#name\\[' + productId + '\\]').length;

            if (alreadyExists) {
                alert('Каталін, ти вже додала цей продукт до замовлення!');
                return;
            }
            var cell1 = row.insertCell(0);
            var cell2 = row.insertCell(1);
            var cell3 = row.insertCell(2);
            var cell4 = row.insertCell(3);

            cell1.innerHTML = '<input type="text" id="name[' + productId + ']" name="name[' + productId + ']" '
                + 'value="' + productName + '" readonly>';
            cell2.innerHTML = '<input type="number" id="cost[' + productId + ']" name="cost[' + productId + ']" '
                + 'value="' + lastCosts[productId] + '">';
            cell3.innerHTML = '<input type="number" id="qty[' + productId + ']" name="qty[' + productId + ']" value="1">';

            cell4.style['text-align'] = 'center';
            cell4.innerHTML = '<span id="delete" ><img src="' + serverUrl + '/media/delete-icon.png"'
                + ' alt="Delete" ' + 'width="20px"></span>';
        });

        $('table#arrival-items-grid').on('click', '#delete', function (e) {
            e.toElement.parentElement.parentElement.parentElement.remove();
        });
    });

</script>
