<?php
/** @var \LovelySpace\Model\ArrivalRepository $arrivalRepository */
$arrivalRepository = \ClassCreator::get(\LovelySpace\Model\ArrivalRepository::class);
$arrivals = $arrivalRepository->getList();

/** @var \LovelySpace\Model\ArrivalItemRepository $arrivalItemRepository */
$arrivalItemRepository = \ClassCreator::get(\LovelySpace\Model\ArrivalItemRepository::class);
?>

<div id="jsGrid"></div>

<script>
    var models = [
        <?php
        /** @var \LovelySpace\Model\Arrival $arrival */
        foreach ($arrivals as $arrival):
        ?>
        {
            'id': '<?= $arrival->getId() ?>',
            'Доставка': '<?= $arrival->getShipment() ?>',
            'Сума': '<?= $arrival->getTotal() . ' грн' ?>',
            'Сума разом з доставкою': '<?= $arrival->getGrandTotal() . ' грн' ?>',
            'Дата': '<?= $arrival->getDate() ?>',
            'Отримані продукти': '<?= $arrivalItemRepository->getProductNamesByArrivalId($arrival->getId()) ?>'
        },
        <?php endforeach; ?>
    ], url = '<?= $arrivalUrl?>';

    $(function() {
        $('#jsGrid').jsGrid({
            height: '120%',
            width: '100%',

            filtering: true,
            editing: false,
            sorting: true,
            paging: true,
            autoload: true,
            controller: {
                loadData: function(filter) {

                    return $.grep(models, function(model) {
                        var filterDate = filter['Дата'].toUpperCase(),
                            modelDate = model['Дата'].toUpperCase(),
                            filterGotProducts = filter['Отримані продукти'].toUpperCase(),
                            modelGotProducts = model['Отримані продукти'].toUpperCase(),
                            filterShipment = filter['Доставка'] ? filter['Доставка'].toString() : '',
                            modelShipment = model['Доставка'] ? model['Доставка'].toString() : '',
                            filterSum = filter['Сума'] ? filter['Сума'].toString() : '',
                            modelSum = model['Сума'] ? model['Сума'].toString() : '',
                            filterSumShipment = filter['Сума разом з доставкою'] ? filter['Сума разом з доставкою'].toString() : '',
                            modelSumShipment = model['Сума разом з доставкою'] ? model['Сума разом з доставкою'].toString() : '';

                        return (!filterDate || modelDate.indexOf(filterDate) > -1)
                            && (typeof filterShipment === 'undefined' || modelShipment.indexOf(filterShipment) > -1)
                            && (!filterGotProducts || modelGotProducts.indexOf(filterGotProducts) > -1)
                            && (typeof filterSum === 'undefined' || modelSum.indexOf(filterSum) > -1)
                            && (typeof filterSumShipment === 'undefined' || modelSumShipment.indexOf(filterSumShipment) > -1)

                    });}
            },
            rowClick: function(args) {
                var id = args.item.id;
                location.href = url + '/edit?id=' + id;
            },
            pageSize: 30,
            data: models,

            fields: [
                {name: 'id', type: 'number', visible: false},
                { name: 'Доставка', type: 'number', width: 40 },
                { name: 'Сума', type: 'number', width: 35 },
                { name: 'Сума разом з доставкою', type: 'number', width: 40 },
                { name: 'Дата', type: 'text', width: 45 },
                { name: 'Отримані продукти', type: 'text', width: 150 }
            ]
        });
    });
</script>
