<?php
/** @var \LovelySpace\Model\Arrival\ArrivalRepository $arrivalRepository */
$arrivalRepository = \ClassCreator::get(\LovelySpace\Model\Arrival\ArrivalRepository::class);
$arrivals = $arrivalRepository->getList();

/** @var \LovelySpace\Model\Arrival\ArrivalItemRepository $arrivalItemRepository */
$arrivalItemRepository = \ClassCreator::get(\LovelySpace\Model\Arrival\ArrivalItemRepository::class);

/** @var \LovelySpace\Model\Shop\ShopRepository $shopRepository */
$shopRepository = \ClassCreator::get(\LovelySpace\Model\Shop\ShopRepository::class);
?>

<div id="jsGrid"></div>

<script>
    var models = [
        <?php
        /** @var \LovelySpace\Model\Arrival\Arrival $arrival */
        foreach ($arrivals as $arrival):
        $shopName = $shopRepository->getNameById($arrival->getShopId())
            ? $shopRepository->getNameById($arrival->getShopId())
            : '';
        ?>
        {
            'id': '<?= $arrival->getId() ?>',
            'Магазин': '<?= $shopName ?>',
            'Сума': '<?= $arrival->getTotal() . ' грн' ?>',
            'Дата': '<?= $arrival->getDate() ?>',
            'Отримані продукти': '<?= $arrivalItemRepository->getProductNamesByArrivalId($arrival->getId()) ?>'
        },
        <?php endforeach; ?>
    ], url = '<?= $arrivalUrl?>';

    $(function() {
        $('#jsGrid').jsGrid({
            height: '120%',
            width: '100%',

            filtering: true,
            editing: false,
            sorting: true,
            paging: true,
            autoload: true,
            controller: {
                loadData: function(filter) {

                    return $.grep(models, function(model) {
                        var filterShop = filter['Магазин'].toUpperCase(),
                            modeShop = model['Магазин'].toUpperCase(),
                            filterDate = filter['Дата'].toUpperCase(),
                            modelDate = model['Дата'].toUpperCase(),
                            filterGotProducts = filter['Отримані продукти'].toUpperCase(),
                            modelGotProducts = model['Отримані продукти'].toUpperCase(),
                            filterSum = filter['Сума'] ? filter['Сума'].toString() : '',
                            modelSum = model['Сума'] ? model['Сума'].toString() : '';

                        return (!filterShop || modeShop.indexOf(filterShop) > -1)
                            && (!filterDate || modelDate.indexOf(filterDate) > -1)
                            && (!filterGotProducts || modelGotProducts.indexOf(filterGotProducts) > -1)
                            && (typeof filterSum === 'undefined' || modelSum.indexOf(filterSum) > -1)

                    });
                }
            },
            rowClick: function(args) {
                var id = args.item.id;
                location.href = url + '/edit?id=' + id;
            },
            pageSize: 30,
            data: models,

            fields: [
                {name: 'id', type: 'number', visible: false},
                { name: 'Магазин', type: 'text', width: 70 },
                { name: 'Сума', type: 'number', width: 35 },
                { name: 'Дата', type: 'text', width: 45 },
                { name: 'Отримані продукти', type: 'text', width: 150 }
            ]
        });
    });
</script>
