<?php
/** @var \LovelySpace\Model\OrderRepository $orderRepository */
$orderRepository = \ClassCreator::get(\LovelySpace\Model\OrderRepository::class);
$orders = $orderRepository->getList();

/** @var \LovelySpace\Model\OrderItemRepository $orderItemRepository */
$orderItemRepository = \ClassCreator::get(\LovelySpace\Model\OrderItemRepository::class);

?>

<table class="full-part">
    <thead>
    <tr>
        <th>Ім'я клієнта</th>
        <th>Сума</th>
        <th>Дата</th>
        <th>Продані продукти</th>
    </tr>
    </thead>
    <?php
    /** @var \LovelySpace\Model\ClientRepository $clientRepository */
    $clientRepository = \ClassCreator::get(\LovelySpace\Model\ClientRepository::class);
    /** @var \LovelySpace\Model\Order $order */
    foreach ($orders as $order) {
        /** @var \LovelySpace\Model\Client $client */
        $client = $clientRepository->get($order->getClientId());
        echo '<tr class="clickable-row" data-href="'. $orderUrl . '/edit?id=' . $order->getId() . '">';
        echo '<td style="display: none">';
        echo $order->getId();
        echo '</td>';
        echo '<td>';
        echo $client->getName();
        echo '</td>';
        echo '<td>';
        echo $order->getTotal() . ' грн';
        echo '</td>';
        echo '<td>';
        echo $order->getDate();
        echo '</td>';
        echo '<td>';
        echo $orderItemRepository->getProductNamesByOrderId($order->getId());
        echo '</td>';
        echo '</tr>';
    }
    ?>
</table>
