<?php
/** @var \LovelySpace\Model\OrderRepository $orderRepository */
$orderRepository = \ClassCreator::get(\LovelySpace\Model\OrderRepository::class);
$orders = $orderRepository->getList();

/** @var \LovelySpace\Model\OrderItemRepository $orderItemRepository */
$orderItemRepository = \ClassCreator::get(\LovelySpace\Model\OrderItemRepository::class);
/** @var \LovelySpace\Model\ClientRepository $clientRepository */
$clientRepository = \ClassCreator::get(\LovelySpace\Model\ClientRepository::class);
?>

<div id="jsGrid"></div>

<script>
    var models = [
        <?php
        /** @var \LovelySpace\Model\Order $order */
        foreach ($orders as $order):
        /** @var \LovelySpace\Model\Client $client */
        $client = $clientRepository->get($order->getClientId());
        ?>
        {
            'id': '<?= $order->getId() ?>',
            'Ім\'я клієнта': '<?= $client->getName() ?>',
            'Сума': '<?= $order->getTotal() . ' грн' ?>',
            'Дата': '<?= $order->getDate() ?>',
            'Продані продукти': '<?= $orderItemRepository->getProductNamesByOrderId($order->getId()) ?>'
        },
        <?php endforeach; ?>
    ], url = '<?= $orderUrl?>';

    $(function() {
        $('#jsGrid').jsGrid({
            height: '120%',
            width: '100%',

            filtering: true,
            editing: false,
            sorting: true,
            paging: true,
            autoload: true,
            controller: {
                loadData: function(filter) {

                    return $.grep(models, function(model) {
                        var filterName = filter['Ім\'я клієнта'].toUpperCase(),
                            modelName = model['Ім\'я клієнта'].toUpperCase(),
                            filterSellProducts = filter['Продані продукти'].toUpperCase(),
                            modelSellProducts = model['Продані продукти'].toUpperCase(),
                            filterSum = filter['Сума'] ? filter['Сума'].toString() : '',
                            modelSum = model['Сума'] ? model['Сума'].toString() : '';

                        return (!filterName || modelName.indexOf(filterName) > -1)
                            && (typeof filterSum === 'undefined' || modelSum.indexOf(filterSum) > -1)
                            && (!filterSellProducts || modelSellProducts.indexOf(filterSellProducts) > -1)
                            && (!filter['Дата'] || model['Дата'].indexOf(filter['Дата']) > -1)
                    });}
            },
            rowClick: function(args) {
                var id = args.item.id;
                location.href = url + '/edit?id=' + id;
            },
            pageSize: 30,
            data: models,

            fields: [
                {name: 'id', type: 'number', visible: false},
                { name: 'Ім\'я клієнта', type: 'text', width: 100 },
                { name: 'Сума', type: 'number', width: 50 },
                { name: 'Дата', type: 'text', width: 50 },
                { name: 'Продані продукти', type: 'text', width: 200 }
            ]
        });
    });
</script>
