<?php
/** @var \classes\Model\SpendingIncome $spendingIncome */
$spendingIncome = \classes\ClassCreator::includeClass(\classes\Model\SpendingIncome::class);
$spendingIncomeByMonthAndYear = $spendingIncome->getSpendingIncomeByMonthAndYear($differenceByDate);

?>

<table id="spending-income">
    <thead>
    <tr>
        <th>Year/month</th>
        <th>Spending</th>
        <th>Income</th>
        <th>Difference</th>
    </tr>
    </thead>
    <?php
    foreach ($spendingIncomeByMonthAndYear as $year => $monthSpendingIncome) {
        foreach ($monthSpendingIncome as $month => $spendingIncome) {
            $spending = isset($spendingIncome['spending']) ? $spendingIncome['spending'] : 0;
            $income = isset($spendingIncome['income']) ? $spendingIncome['income'] : 0;
            echo '<tr>';
            echo '<td>';
            echo $year . '/' . $month;
            echo '</td>';
            echo '<td>';
            echo $spending;
            echo '</td>';
            echo '<td>';
            echo $income;
            echo '</td>';
            echo '<td>';
            echo $income + $spending;
            echo '</td>';
            echo '</tr>';
        }
    }
    ?>
</table>
