<?php
/** @var \LovelySpace\Model\Product\ProductRepository $productRepository */
$productRepository = \ClassCreator::get(\LovelySpace\Model\Product\ProductRepository::class);
$products = $productRepository->getList();

/** @var \LovelySpace\Model\Product\ProductStockRepository $productStockRepository */
$productStockRepository = \ClassCreator::get(\LovelySpace\Model\Product\ProductStockRepository::class);
$productStocks = $productStockRepository->getList();
?>
<div id="jsGrid"></div>

<script>
    var products = [
        <?php
        $costs = 0;
        /** @var \LovelySpace\Model\Product\Product $product */
        foreach ($products as $product):
        list($costsLine, $cost)
            = $earningRepository->getCostLineByReportAndProductId($reportArrivals, $product->getId());
        $costs += $cost;
        ?>
        {
            'id': '<?= $product->getId()?>',
            'Ім\'я продукта': '<?= $product->getName()?>',
            'Ціна': <?= $product->getPrice()?>,
            'В наявності': <?= isset($productStocks[$product->getId()]) ? $productStocks[$product->getId()]->getQty() : 0 ?>,
            'Собівартість': '<?= $costsLine ?>'
        },
        <?php endforeach; ?>
    ];

    $(function() {
        $('#jsGrid').jsGrid({
            height: '200%',
            width: '100%',

            filtering: true,
            editing: false,
            sorting: true,
            paging: true,
            autoload: true,
            controller: {
                loadData: function(filter) {
                    return $.grep(products, function(product) {
                        var filterName = filter['Ім\'я продукта'].toUpperCase(),
                            productName = product['Ім\'я продукта'].toUpperCase();

                        return (!filterName || productName.indexOf(filterName) > -1)
                            && (!filter['Ціна'] || product['Ціна'] === parseInt(filter['Ціна']))
                            && (!filter['В наявності'] || product['В наявності'] === parseInt(filter['В наявності']))
                    });}
            },
            pageSize: 100,
            data: products,

            fields: [
                { name: 'id', type: 'number', visible: false},
                { name: 'Ім\'я продукта', type: 'text', width: 400 },
                { name: 'Ціна', type: 'number', width: 50 },
                { name: 'В наявності', type: 'text', width: 50 },
                { name: 'Собівартість', type: 'text', width: 150 }
            ]
        });
    });
</script>
<?= $costs ?>
