<?php
/** @var \LovelySpace\Model\ProductRepository $productRepository */
$productRepository = \ClassCreator::get(\LovelySpace\Model\ProductRepository::class);
$productId = null;

if (!empty($_POST)) {
    $productRepository->save($_POST);

    header('Location: '. $serverUrl . '/lovely_space/product');
    die;
}

if (!empty($_GET)) {
    $productId = isset($_GET['id']) ? $_GET['id'] : null;
}

/** @var \LovelySpace\Model\Product $product */
$product = $productRepository->get($productId);

/** @var \LovelySpace\Model\Resource\ArrivalItem $arrivalItem */
$arrivalItem = \ClassCreator::get(\LovelySpace\Model\Resource\ArrivalItem::class);
$lastCost = $arrivalItem->getLastCostForProductByProductId($productId);

/** @var \LovelySpace\Model\ProductStockManager $productStockManager */
$productStockManager = \ClassCreator::get(\LovelySpace\Model\ProductStockManager::class);
$stocksByProductId = $productStockManager->getProductStocksByProductId();
$qty =  isset($stocksByProductId[$product->getId()]['qty']) ? $stocksByProductId[$product->getId()]['qty'] : 0;
?>
<div class="edit-product-form">
    <div class="title"><span class="title">Сторінка редагування продукту</span></div>
    <form action="" method="post" id="edit">
        <div style="display: none">
            <label for="id">ID:</label>
            <input type="number" id="id" name="id" value="<?= $productId; ?>">
        </div>
        <div>
            <div class="col-30">
                <label class="required" for="name">Назва:</label>
            </div>
            <div class="col-70">
                <input type="text" id="name" name="name" value="<?= $product->getName(); ?>" required>
            </div>
        </div>
        <div>
            <div class="col-30">
                <label class="required" for="price">Ціна:</label>
            </div>
            <div class="col-70">
                <input type="number" id="price" name="price" value="<?= $product->getPrice(); ?>" required>
            </div>
        </div>
        <?php if ($productId): ?>
            <div>
                <div class="col-30">
                    <label class="required" for="cost">Остання собівартість:</label>
                </div>
                <div class="col-70">
                    <input type="number" id="cost" name="cost" value="<?= $lastCost; ?>" disabled>
                </div>
            </div>
            <div>
                <div class="col-30">
                    <label class="required" for="qty">Наявна кількість:</label>
                </div>
                <div class="col-70">
                    <input type="number" id="qty" name="qty" value="<?= $qty; ?>" disabled>
                </div>
            </div>
        <?php endif; ?>
    </form>
    <button class="half" onclick="location.href = '<?= $_SERVER['HTTP_REFERER'] ?>'" id="back-button">Назад</button>
    <button class="half" type="submit" form="edit" id="save-product-button">Зберегти</button>
</div>
