<?php
/** @var \LovelySpace\Model\Spending\SpendingRepository $spendingRepository */
$spendingRepository = \ClassCreator::get(\LovelySpace\Model\Spending\SpendingRepository::class);
$spendingId = null;

if (!empty($_POST)) {
    $spendingRepository->save($_POST);

    header('Location: '. $serverUrl . '/lovely_space/spending');
    die;
}

if (!empty($_GET)) {
    $spendingId = isset($_GET['id']) ? $_GET['id'] : null;
}

/** @var \LovelySpace\Model\Spending\Spending $spending */
$spending = $spendingRepository->get($spendingId);

?>
<div class="edit-product-form" align="left">
    <div class="title"><span class="title">Витрати</span></div>
    <form action="" method="post" id="edit">
        <div style="display: none">
            <div class="full-with-margin">
                <label for="id">ID:</label>
            </div>
            <div class="full-with-margin">
                <input type="number" id="id" name="id" value="<?= $spendingId; ?>">
            </div>
        </div>
        <div>
            <div class="full-with-margin">
                <label class="required" for="sum">Сума:</label>
            </div>
            <div class="full-with-margin">
                <input type="number" id="sum" name="sum" value="<?= $spending->getSum(); ?>" required>
            </div>
        </div>
        <div>
            <div class="full-with-margin">
                <label class="required" for="date">Дата:</label>
            </div>
            <div class="full-with-margin">
                <input type="text" class="datepicker" id="date" name="date" value="<?= $spending->getDate()
                    ? $spending->getDate() :  date('Y-m-d'); ?>" required>
            </div>
        </div>
        <div>
            <div class="full-with-margin">
                <label class="required" for="comment">Коментар:</label>
            </div>
            <div class="full-with-margin">
                <input type="text" id="comment" name="comment" value="<?= $spending->getComment(); ?>" required>
            </div>
        </div>
    </form>
    <div>
        <button class="half" onclick="location.href = '<?= $_SERVER['HTTP_REFERER']?>'" id="back-button">Назад</button>
        <button class="half" form="edit" type="submit" id="save-spending-button">Зберегти</button>
    </div>
</div>
