<footer>
    <div class="container">
        <div class="col-1-3"></div>
        <div class="col-1-3"></div>
        <div class="col-1-3"></div>
    </div>
</footer>

<script>
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });

        $('.select2').select2({
            theme: 'bootstrap'
        });

        $(function () {
            $(".datepicker").datepicker({ dateFormat: 'yy-mm-dd' });
        });
    });
    <?php if ($isLovelySpace): ?>
    (function() {
        var link = document.querySelector("link[rel*='icon']") || document.createElement('link');
        link.type = 'image/x-icon';
        link.rel = 'shortcut icon';
        link.href = '<?php echo $serverUrl;?>/media/lovely-logo.png';
        document.getElementsByTagName('head')[0].appendChild(link);
    })();
    <?php endif; ?>
</script>
