<?php
if (!empty($_POST)) {
    /** @var \FinanceManagement\Model\FinanceDetails $financeDetails */
    $financeDetails = \ClassCreator::get(\FinanceManagement\Model\FinanceDetails::class);
    $financeDetails->createDuplicateForDate($_POST['date']);
    echo "<meta http-equiv='refresh' content='0'>";
}

$financesLimit = 10;

/** @var \FinanceManagement\Model\Finance $finance */
$finance = ClassCreator::get(\FinanceManagement\Model\Finance::class);
$finances = $finance->getFinances();
$reverseFinance = array_reverse($finances, true);
$lastSum = 0;
$differenceByDate = [];
foreach ($finances as $date => $sums) {
    $differenceByDate[$date] = $sums['sumUah'] - $lastSum;
    $lastSum = $sums['sumUah'];
}

/** @var \FinanceManagement\Model\Rate $rate */
$rate = \ClassCreator::get(\FinanceManagement\Model\Rate::class);
?>

<div class="left add-finance-details-form">
    <form action="" method="post" id="finance_details">
        <label for="date">Date:</label>
        <input type="text" id="datepicker" value="<?php echo date('Y-m-d'); ?>" name="date" required>
        <input type="submit" value="Add">
    </form>
</div>

<table class="full-part">
    <thead>
    <tr>
        <th>Date</th>
        <th>Sum UAH</th>
        <th>Active Sum UAH</th>
        <th>Sum USD</th>
        <th>Active Sum USD</th>
        <th>Diff with last</th>
        <th>Comment</th>
    </tr>
    </thead>
    <?php
    $i = 0;
    foreach ($reverseFinance as $date => $sums) {
        echo '<tr class="clickable-row" data-href="/finance_details?date=' . $date . '">';
        echo '<td>';
        echo $date;
        echo '</td>';
        echo '<td>';
        echo $sums['sumUah'];
        echo '</td>';
        echo '<td>';
        echo $sums['activeSumUah'];
        echo '</td>';
        echo '<td>';
        echo $rate->getUsdSumByCurrency($sums['sumUah'], 'UAH');
        echo '</td>';
        echo '<td>';
        echo $rate->getUsdSumByCurrency($sums['activeSumUah'], 'UAH');
        echo '</td>';
        echo '<td>';
        echo $differenceByDate[$date];
        echo '</td>';
        echo '<td>';
        echo $sums['comment'];
        echo '</td>';
        echo '</tr>';
        if ($i == $financesLimit) {
            break;
        }
        $i++;
    }
    ?>
</table>
<?php
include 'finance/spending-income.phtml';
?>

<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>
