<?php
/** @var \FinanceManagement\Model\Stock $stock */
$stock = \ClassCreator::get(\FinanceManagement\Model\Stock::class);
$stocks = $stock->getStocks();

/** @var \FinanceManagement\Model\Rate $rate */
$rate = \ClassCreator::get(\FinanceManagement\Model\Rate::class);
$rates = $rate->getRates();

$date = isset($_GET['date']) ? $_GET['date'] : null;

if ($date):
/** @var \FinanceManagement\Model\FinanceDetails $financeDetail */
$financeDetail = \ClassCreator::get(\FinanceManagement\Model\FinanceDetails::class);
$financeDetails = $financeDetail->getFinanceDetailsByDate($date);

list($sumUah, $activeSumUah) = $financeDetail->getSumsUahByDate($date);

$sumUsd = $rate->getUsdSumByCurrency($sumUah, 'UAH');
$activeSumUsd = $rate->getUsdSumByCurrency($activeSumUah, 'UAH');

?>
<h1>Finance details for the date: <?php echo $date ?></h1>

<div>
    <table class="full-part">
        <thead>
        <tr>
            <th>ID</th>
            <th>Stock</th>
            <th>Source</th>
            <th>Sum</th>
            <th>Currency</th>
            <th>Active</th>
            <th>Date</th>
            <th>Comment</th>
            <th class="delete">Delete</th>
        </tr>
        </thead>
        <?php
        foreach ($financeDetails as $financeDetail) {
            echo '<tr>';
            echo '<td>';
            echo $financeDetail['id'];
            echo '</td>';
            echo '<td>';
            echo $financeDetail['stock'];
            echo '</td>';
            echo '<td>';
            echo $financeDetail['source'];
            echo '</td>';
            echo '<td>';
            ?> <input type="text" id="<?php echo $financeDetail['id'] . '_sum'; ?>" value="<?php
            echo $financeDetail['sum']; ?> ">
            <img class="update_value" id="<?php echo $financeDetail['id'] . '_sum'; ?>" src="media/update-icon.png"
                 alt="Update" width="20px">
            <?php
            echo '</td>';
            echo '<td>';
            echo $financeDetail['currency'];
            echo '</td>';
            echo '<td>';
            echo $financeDetail['active'];
            echo '</td>';
            echo '<td>';
            echo $financeDetail['date'];
            echo '</td>';
            echo '<td>';
            ?> <input type="text" id="<?php echo $financeDetail['id'] . '_comment'; ?>" value="<?php
            echo $financeDetail['comment']; ?> ">
            <img class="update_value" id="<?php echo $financeDetail['id'] . '_comment'; ?>" src="media/update-icon.png"
                 alt="Update" width="20px">
            <?php
            echo '</td>';
            ?>
            <td style="text-align: center;">
                <a href="<?php echo '/finance_details/delete?id=' . $financeDetail['id']
                ?>">
                    <img src="media/delete-icon.png" alt="Delete" width="20px">
                </a>
            </td>
            <?php
            echo '</tr>';
        }
        ?>
    </table>
</div>

<div class="third-part right">
    <table>
        <thead>
        <tr>
            <th>Sum</th>
            <th>Currency</th>
        </tr>
        </thead>
        <tr>
            <td><?php echo $sumUah; ?></td>
            <td>UAH</td>
        </tr>
        <tr>
            <td><?php echo $sumUsd; ?></td>
            <td>USD</td>
        </tr>
        <tr>
            <td><?php echo $activeSumUah; ?></td>
            <td>UAH-active</td>
        </tr>
        <tr>
            <td><?php echo $activeSumUsd; ?></td>
            <td>USD-active</td>
        </tr>
    </table>
</div>
<?php endif; ?>

<div class="left add-finance-details-form">
    <form id="stock-on-details-form" action="finance_details/post" method="post" id="finance_details">
        <div>
            <label for="stock">Stock:</label>
            <select name="stock" id="stock">
                <?php foreach ($stocks as $stock): ?>
                    <option value="<?php echo $stock['name']; ?>"><?php echo $stock['name']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label class="required" for="source">Source:</label>
            <input type="text" id="source" name="source" required>
        </div>
        <div>
            <label class="required" for="sum">Sum:</label>
            <input type="number" id="sum" name="sum" min="0" required>
        </div>
        <div>
            <label for="currency">Currency</label>
            <select name="currency" id="currency">
                <?php foreach ($rates as $rate): ?>
                    <option><?php echo $rate['currency']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label class="required" for="date">Date:</label>
            <input type="text" id="datepicker" value="<?php
            if ($date) {
                echo $date;
            } else {
                echo date('Y-m-d');
            }
            ?>" name="date" required>
        </div>
        <div>
            <label for="date">Is Active</label>
            <input type="checkbox" name="active" checked="checked">
        </div>

        <input type="submit" value="Add">
    </form>
</div>
<script>
    $(function () {
        $("#datepicker").datepicker({ dateFormat: 'yy-mm-dd' });
    });

    $('.update_value').click(function (e) {
        var elementId = e.currentTarget.id,
            value = $('input#' + elementId).val(),
            id = elementId.split('_')[0],
            fieldToUpdate = elementId.split('_')[1];

        location.href = '/finance_details/update?id=' + id + '&' + fieldToUpdate + '=' + value;
    })
</script>
