<?php
if (!isset($_POST['password'])) {
    include 'password.phtml';
    return;
} else {
    if ($_POST['password'] != 'zxc') {
        include 'password.phtml';
        return;
    }
}

$financesLimit = 10;

/** @var \classes\Model\Finance $finance */
$finance = \classes\ClassCreator::includeClass(\classes\Model\Finance::class);
$finances = $finance->getFinances();
$reverseFinance = array_reverse($finances, true);
$lastSum = 0;
$differenceByDate = [];
foreach ($finances as $date => $sums) {
    $differenceByDate[$date] = $sums['sumUah'] - $lastSum;
    $lastSum = $sums['sumUah'];
}

/** @var \classes\Model\Rate $rate */
$rate = \classes\ClassCreator::includeClass(\classes\Model\Rate::class);
?>

<div class="left add-finance-details-form">
    <form action="finance/post" method="post" id="finance_details">
        <div>
            <label for="date">Date:</label>
            <input type="text" id="datepicker" value="<?php echo date('o-m-d'); ?>" name="date" required>
            <input type="submit" value="Add">
        </div>
    </form>
</div>

<table class="full-part">
    <thead>
    <tr>
        <th>Date</th>
        <th>Sum UAH</th>
        <th>Active Sum UAH</th>
        <th>Sum USD</th>
        <th>Active Sum USD</th>
        <th>Diff with last</th>
        <th>Comment</th>
    </tr>
    </thead>
    <?php
$i = 0;
    foreach ($reverseFinance as $date => $sums) {
        echo '<tr class="clickable-row" data-href="/finance_details?date=' . $date . '">';
        echo '<td>';
        echo $date;
        echo '</td>';
        echo '<td>';
        echo $sums['sumUah'];
        echo '</td>';
        echo '<td>';
        echo $sums['activeSumUah'];
        echo '</td>';
        echo '<td>';
        echo $rate->getUsdSumByCurrency($sums['sumUah'], 'UAH');
        echo '</td>';
        echo '<td>';
        echo $rate->getUsdSumByCurrency($sums['activeSumUah'], 'UAH');
        echo '</td>';
        echo '<td>';
        echo $differenceByDate[$date];
        echo '</td>';
        echo '<td>';
        echo $sums['comment'];
        echo '</td>';
        echo '</tr>';
        if ($i == $financesLimit) {
            break;
        }
        $i++;
    }
    ?>
</table>
<?php
include 'finance/spending-income.phtml';
?>

<script>
    $(function () {
        $("#datepicker").datepicker();
    });

    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
    });
</script>
