<?php
/** @var \classes\Model\Finance $finance */
$finance = \classes\ClassCreator::includeClass(\classes\Model\Finance::class);
$finances = $finance->getFinances();

/** @var \classes\Model\Rate $rate */
$rate = \classes\ClassCreator::includeClass(\classes\Model\Rate::class);
?>

<table class="full-part">
    <thead>
    <tr>
        <th>Date</th>
        <th>Sum UAH</th>
        <th>Active Sum UAH</th>
        <th>Sum USD</th>
        <th>Active Sum USD</th>
        <th>Diff with last</th>
    </tr>
    </thead>
    <?php
    $lastSum = 0;
    foreach ($finances as $date => $sums) {
        echo '<tr class="clickable-row" data-href="/finance_details?date=' . $date . '">';
        echo '<td>';
        echo $date;
        echo '</td>';
        echo '<td>';
        echo $sums['sumUah'];
        echo '</td>';
        echo '<td>';
        echo $sums['activeSumUah'];
        echo '</td>';
        echo '<td>';
        echo $rate->getUsdSumByCurrency($sums['sumUah'], 'UAH');
        echo '</td>';
        echo '<td>';
        echo $rate->getUsdSumByCurrency($sums['activeSumUah'], 'UAH');
        echo '</td>';
        ?>
    <?php
        echo '<td>';
        echo $sums['sumUah'] - $lastSum;
        echo '</td>';
        echo '</tr>';
        $lastSum = $sums['sumUah'];
    }
    ?>
</table>

<div class="left add-finance-details-form">
    <form action="finance/post" method="post" id="finance_details">
        <div>
            <label for="date">Date:</label>
            <input type="text" id="datepicker" value="<?php echo date('m/d/o'); ?>" name="date" required>
        </div>

        <input type="submit" value="Add for the date">
    </form>
</div>

<script>
    $(function () {
        $("#datepicker").datepicker();
    });

    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
    });
</script>
