<?php
/** @var \classes\Model\Rate $rate */
$rate = \classes\ClassCreator::includeClass(\classes\Model\Rate::class);
$rates = $rate->getRates();
?>
<div>
<table align="center">
    <thead>
    <tr>
        <th>ID</th>
        <th>Currency</th>
        <th>Coefficient</th>
    </tr>
    </thead>
    <?php
    foreach ($rates as $rate) {
        echo '<tr>';
        echo '<td>';
        echo $rate['id'];
        echo '</td>';
        echo '<td>';
        echo $rate['currency'];
        echo '</td>';
        echo '<td>';
        echo $rate['coefficient'];
        echo '</td>';
        echo '</tr>';
    }
    ?>
</table>
</div>

<div class="add-rate-form" align="center">
    <form action="rates/post" method="post" id="rate">
        <div>
            <label for="currency">Currency:</label>
            <select name="currency" id="currency">
                <option value="UAH">UAH</option>
                <option value="USD">USD</option>
                <option value="EUR">EUR</option>
            </select>
        </div>
        <div>
            <label class="required" for="coefficient">Coefficient:</label>
            <input type="text" id="coefficient" name="coefficient" required>
        </div>
        <input type="submit" value="Add or Update">
    </form>
</div>
