<?php
/** @var \LovelySpace\Model\ShopRepository $shopRepository */
$shopRepository = \ClassCreator::get(\LovelySpace\Model\ShopRepository::class);
$shopId = null;

if (!empty($_POST)) {
    $shopRepository->save($_POST);

    header('Location: '. $serverUrl . '/lovely_space/shop');
    die;
}

if (!empty($_GET)) {
    $shopId = isset($_GET['id']) ? $_GET['id'] : null;
}

/** @var \LovelySpace\Model\Shop $shop */
$shop = $shopRepository->get($shopId);

?>
<div class="edit-product-form" align="left">
    <div class="title"><span class="title">Магазин</span></div>
    <form action="" method="post" id="edit">
        <div style="display: none">
            <div class="full-with-margin">
                <label for="id">ID:</label>
            </div>
            <div class="full-with-margin">
                <input type="number" id="id" name="id" value="<?= $shopId; ?>">
            </div>
        </div>
        <div>
            <div class="full-with-margin">
                <label class="required" for="name">Ім'я:</label>
            </div>
            <div class="full-with-margin">
                <input type="text" id="name" name="name" value="<?= $shop->getName(); ?>" required>
            </div>
        </div>
    </form>
    <div>
        <button class="half" onclick="location.href = '<?= $_SERVER['HTTP_REFERER']?>'" id="back-button">Назад</button>
        <button class="half" form="edit" type="submit" id="save-shop-button">Зберегти</button>
    </div>
</div>
