<?php
if (!empty($_POST)) {
    /** @var \FinanceManagement\Model\FinanceDetails $financeDetails */
    $financeDetails = \ClassCreator::get(\FinanceManagement\Model\FinanceDetails::class);
    $financeDetails->createDuplicateForDate($_POST['date']);

    header('Location: ' . '/finance_details?date=' . $_POST['date'], true, 302);
    die();
} else {
    header('Location: ' . $_SERVER["HTTP_REFERER"], true, 302);
    die();
}
