<?php
/** @var \LovelySpace\Model\ClientRepository $clientRepository */
$clientRepository = \ClassCreator::get(\LovelySpace\Model\ClientRepository::class);
$clientId = null;

if (!empty($_POST)) {
    $clientRepository->save($_POST);

    header('Location: '. $serverUrl . '/lovely_space/client');
    die;
}

if (!empty($_GET)) {
    $clientId = isset($_GET['id']) ? $_GET['id'] : null;
}

/** @var \LovelySpace\Model\Client $client */
$client = $clientRepository->get($clientId);

?>
<div class="edit-product-form" align="left">
    <div class="title"><span class="title">Сторінка редагування клієнта</span></div>
    <form action="" method="post" id="edit">
        <div style="display: none">
            <div class="col-25">
                <label for="id">ID:</label>
            </div>
            <div class="col-75">
                <input type="number" id="id" name="id" value="<?= $clientId; ?>">
            </div>
        </div>
        <div>
            <div class="col-25">
                <label class="required" for="name">Ім'я:</label>
            </div>
            <div class="col-75">
                <input type="text" id="name" name="name" value="<?= $client->getName(); ?>" required>
            </div>
        </div>
        <div>
            <div class="col-25">
                <label for="phone">Телефон</label>
            </div>
            <div class="col-75">
                <input type="text" id="phone" name="phone" value="<?= $client->getPhone() ? $client->getPhone() : '+380'; ?>">
            </div>
        </div>
    </form>
    <div>
        <button onclick="location.href = '<?= $_SERVER['HTTP_REFERER']?>'" id="back-button">Назад</button>
        <button form="edit" type="submit" id="save-client-button">Зберегти</button>
    </div>
</div>
