<?php
/** @var \LovelySpace\Model\ClientRepository $clientRepository */
$clientRepository = \ClassCreator::get(\LovelySpace\Model\ClientRepository::class);
$clients = $clientRepository->getList();
?>

<div id="jsGrid"></div>

<script>
    var models = [
        <?php
        /** @var \LovelySpace\Model\Client $model */
        foreach ($clients as $model): ?>
        {
            'id': '<?= $model->getId()?>',
            'Ім\'я': '<?= $model->getName()?>',
            'Телефон': '<?= $model->getPhone()?>'
        },
        <?php endforeach; ?>
    ], url = '<?= $clientUrl?>';

    $(function() {
        $('#jsGrid').jsGrid({
            height: '120%',
            width: '100%',

            filtering: true,
            editing: false,
            sorting: true,
            paging: true,
            autoload: true,
            controller: {
                loadData: function(filter) {
                    return $.grep(models, function(model) {
                        var filterName = filter['Ім\'я'].toUpperCase(),
                            modelName = model['Ім\'я'].toUpperCase();

                        return (!filterName || modelName.indexOf(filterName) > -1)
                            && (!filter['Телефон'] || model['Телефон'].indexOf(filter['Телефон']) > -1)
                    });}
            },
            rowClick: function(args) {
                var id = args.item.id;
                location.href = url + '/edit?id=' + id;
            },
            pageSize: 30,
            data: models,

            fields: [
                { name: 'id', type: 'number', visible: false},
                { name: 'Ім\'я', type: 'text', width: 150 },
                { name: 'Телефон', type: 'text', width: 50 }
            ]
        });
    });
</script>
